#ifndef MOON_TONESOURCE_H
#define MOON_TONESOURCE_H

#include "SingleSource.h"

namespace maudio {
	
	/// \addtogroup audio
	/// @{

	/// \brief Audio source that can play a single sample generated by ToneGenerator
	/// \ingroup components
	class ToneSource : public SingleSource {
	public:
		ToneSource();
		ToneSource(const ToneSource& source, const osg::CopyOp& copyop = osg::CopyOp::SHALLOW_COPY);
		META_Object(maudio, ToneSource);

		virtual void parseXML(const TiXmlElement *element);
		virtual void writeXML(TiXmlElement *element) const;
	};
	
	/// @}
	
}

#endif
